src/Entity/Marque.php
<?php

namespace App\Entity;

use App\Repository\MarqueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MarqueRepository::class)]
class Marque
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo = null;

    #[ORM\OneToMany(mappedBy: 'marque', targetEntity: Model::class)]
    private Collection $marque;

    public function __construct()
    {
        $this->marque = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }

    #[ORM\PostRemove]
    public function deleteImage()
    {
        if ($this->logo != null) {
            unlink(__DIR__ . '/../../public/uploads/' . $this->logo);
        }
        return true;
    }

    /**
     * @return Collection<int, Model>
     */
    public function getMarque(): Collection
    {
        return $this->marque;
    }

    public function addMarque(Model $marque): static
    {
        if (!$this->marque->contains($marque)) {
            $this->marque->add($marque);
            $marque->setMarque($this);
        }

        return $this;
    }

    public function removeMarque(Model $marque): static
    {
        if ($this->marque->removeElement($marque)) {
            // set the owning side to null (unless already changed)
            if ($marque->getMarque() === $this) {
                $marque->setMarque(null);
            }
        }

        return $this;
    }
}

src/Form/MarqueType.php
<?php

namespace App\Form;

use App\Entity\Marque;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;


class MarqueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('date_creation')
            ->add('logo', FileType::class, [
                'label' => 'Logo (jpg, png)',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpg',
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid image',
                    ])
                ],
            ])
            ->add('Envoyer', SubmitType::class);
        ;
        
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Marque::class,
        ]);
    }
}

src/Controller/MarqueController.php
<?php

namespace App\Controller;

use App\Entity\Marque;
use App\Form\MarqueType;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/marque')]
class MarqueController extends AbstractController
{
    #[Route('/', name: 'app_marque')]
    public function index(EntityManagerInterface $em, Request $request, LoggerInterface $logger): Response
    {
        $marque = new Marque();
        $form = $this->createForm(MarqueType::class, $marque);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $logger->error('1');
            $logoFile = $form->get('logo')->getData();
            if ($logoFile) {
                $logger->error('2');
                $newFilename = uniqid() . '.' . $logoFile->guessExtension();

                try {
                    $logger->error('3');
                    $logoFile->move(
                        $this->getParameter('upload_directory'),
                        $newFilename
                    );
                    $logger->error('4');
                } catch (FileException $e) {
                    $this->addFlash('danger', 'Impossible d\'ajouter l\'image');
                }

                $marque->setLogo($newFilename);
            }

            $em->persist($marque);
            $em->flush();

            $this->addFlash('success', 'Marque ajouté ✔️');
        }

        // Récupération des catégories (SELECT *)
        $marques = $em->getRepository(Marque::class)->findAll();


        return $this->render('marque/index.html.twig', [
            'marques' => $marques,
            'ajout' => $form->createView()
        ]);
    }
    #[Route('/{id}', name: 'marque')]
    public function marque(Marque $marque = null, Request $request, EntityManagerInterface $em): Response
    {
        if ($marque == null) {
            $this->addFlash('danger', 'Marque introuvable arrête 😭😭😭 !!');
            return $this->redirectToRoute('app_marque');
        }

        $form = $this->createForm(MarqueType::class, $marque);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $logoFile = $form->get('logo')->getData();
            if ($logoFile) {
                $newFilename = uniqid() . '.' . $logoFile->guessExtension();

                try {
                    $logoFile->move(
                        $this->getParameter('upload_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash('danger', 'Impossible de modifier l\'image');
                }

                $marque->setLogo($newFilename);
            }

            $em->persist($marque);
            $em->flush();

            $this->addFlash('success', 'Marque mise à jour ☠️☠️☠️');
        }
        $marques = $em->getRepository(Marque::class)->findAll();

        return $this->render('marque/show.html.twig', [
            'marques' => $marques,
            'uneMarque' => $marque,
            'edit' => $form->createView()
        ]);
    }

    #[Route('/delete/{id}', name: 'marque_delete')]
    public function delete(Marque $marque = null, EntityManagerInterface $em)
    {
        if ($marque == null) {
            $this->addFlash('danger', 'Marque introuvable arrête 😭😭😭 !!');
            return $this->redirectToRoute('app_marque');
        }
        $em->remove($marque);
        $em->flush();


        $this->addFlash('warning', 'Marque supprimée, t\'es fière ? 🙄');
        return $this->redirectToRoute('app_marque');
    }
}

templates/marque/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}APP Kidd
{% endblock %}

{% block body %}
	<div>
		<h1 class="text-center">Liste des marques</h1>
	</div>
	<div class="container">
		<div>
			<button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Ajouter une marque 😁</button>
		</div>
		<table class="table table-striped text-center">
			<thead>
				<tr>
					<th scope="col">Logo Marque</th>
					<th scope="col">Nom</th>
					<th scope="col">Date création</th>
					<th scope="col">Action</th>
				</tr>
			</thead>
			<tbody>
				{% for marque in marques %}
					<tr>
						<td class="w-25">
							{% if marque.logo is defined and marque.logo is not empty %}
								<img src="{{ asset('uploads/' ~ marque.logo) }}" class="img-fluid img-thumbnail w-25" alt="...">
							{% else %}
								Pas d'images désolé 😂😂😂😂
							{% endif %}
						</td>
						<td>{{ marque.nom }}</td>
						<td class="w-25"><input type="date" value="{{marque.dateCreation|date('Y-m-d')}}" class="form-control text-center" readonly="readonly"></td>
						<td>
							<a class='text-decoration-none' id='btn-view' href="{{path('marque', {'id': marque.id})}}">
								<button class="btn btn-outline-info">👀</button>
							</a>
							<a class='text-decoration-none' href="{{path('marque_delete', {'id': marque.id})}}">
								<button class="btn btn-outline-danger">❌</button>
							</a>
						</td>
					</tr>
				{% else %}
					<tr>
						<td colspan="4" class="text-center">Pas de marques Mr 😑</td>
					</tr>
				{% endfor %}
			</tbody>


		</table>
	</div>
	<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
		<form method="post" action="" enctype="multipart/form-data">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h1 class="modal-title fs-5" id="staticBackdropLabel">Ajouter une marque</h1>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body">
						{{ form(ajout) }}

						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
							<button type="submit" class="btn btn-success">Sauvegarder</button>
						</div>
					</div>
				</div>
			</form>
		</div>
	{% endblock %}

templates/marque/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container w-50">
		<div class="py-5 text-center">
			<img src="{{ asset('uploads/' ~ uneMarque.logo) }}" class="img-fluid img-thumbnail w-25 d-block mx-auto mb-4" alt="...">
			<p class="lead">Modifier votre marque.</p>
		</div>

		<div class="row g-5">
			<div class="col-md-4 col-lg-4 order-md-last">
				<h4 class="d-flex justify-content-between align-items-center mb-3">
					<span class="text-primary">La marque
					</span>
				</h4>
				<ul class="list-group mb-3">
					<li class="list-group-item d-flex justify-content-between lh-sm">
						<div>
							<h6 class="my-0">Nom
							</h6>
						</div>
						<span class="text-muted">{{uneMarque.nom}}</span>
					</li>
					<li class="list-group-item d-flex justify-content-between lh-sm">
						<div>
							<h6 class="my-0">Date
							</h6>
						</div>
						<span class="text-muted">{{uneMarque.dateCreation|date('Y-m-d')}}</span>
					</li>
				</ul>
			</div>
			<div class="col-md-7 col-lg-7 order-md-last">
				<h4 class="d-flex justify-content-between align-items-center mb-3">
					<span class="text-primary">Modifications
					</span>
				</h4>
                {{form(edit)}}
			</div>
		</div>
	</div>
{% endblock %}