src/Entity/Model.php
<?php

namespace App\Entity;

use App\Repository\ModelRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ModelRepository::class)]
class Model
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(nullable: true)]
    private ?float $prix_depart = null;

    #[ORM\ManyToOne(targetEntity: Marque::class, inversedBy: 'models')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Marque $marque = null;


    public function getId(): ?int
    {
        return $this->id;
    }


    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrixDepart(): ?float
    {
        return $this->prix_depart;
    }

    public function setPrixDepart(?float $prix_depart): static
    {
        $this->prix_depart = $prix_depart;

        return $this;
    }
    public function getMarque(): ?Marque
    {
        return $this->marque;
    }

    public function setMarque(?Marque $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

}

src/Form/ModelType.php
<?php

namespace App\Form;

use App\Entity\Marque;
use App\Entity\Model;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ModelType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prix_depart')
            ->add('marque', EntityType::class, [
                'class' => Marque::class,
'choice_label' => 'nom',
            ])
            ->add('Envoyer', SubmitType::class);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Model::class,
        ]);
    }
}

src/Controller/ModelController.php
<?php

namespace App\Controller;

use App\Entity\Model;
use App\Form\ModelType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
#[Route('/model')]
class ModelController extends AbstractController
{
    #[Route('/', name: 'app_model')]
    public function index(EntityManagerInterface $em, Request $request): Response{
        $model = new Model();
        $form = $this->createForm(ModelType::class, $model);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){

            $em->persist($model);
            $em->flush();
            $this->addFlash('success','Model ajouté ✔️');
        }
        
        // Récupération des catégories (SELECT *)
        $models = $em->getRepository(Model::class)->findAll();


        return $this->render('model/index.html.twig', [
            'models' => $models,  
            'ajout'=> $form->createView()
        ]);
    }
    #[Route('/{id}', name: 'model')]
    public function model (Model $model = null, Request $request, EntityManagerInterface $em) :Response{
        if ($model == null) {
            $this->addFlash('danger', 'Model introuvable arrête 😭😭😭 !!');
            return $this->redirectToRoute('app_model');
        }

        $form = $this->createForm(ModelType::class, $model);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($model);
            $em->flush();

            $this->addFlash('success', 'Model mise à jour ☠️☠️☠️');
        }
        $models = $em->getRepository(Model::class)->findAll();

        return $this->render('model/show.html.twig', [
            'models' => $models,  
            'UnModel' => $model,
            'edit' => $form->createView()   
        ]);
    }

    #[Route('/delete/{id}', name:'model_delete')]
    public function delete(Model $model= null, EntityManagerInterface $em){
        if($model == null){
            $this->addFlash('danger', 'Model introuvable arrête 😭😭😭 !!');
            return $this->redirectToRoute('app_model');
        }
        $em->remove($model);
        $em->flush();

        
        $this->addFlash('warning', 'model supprimée, t\'es fière ? 🙄');
        return $this->redirectToRoute('app_model');
    }
    
}

templates/model/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div>
		<h1 class="text-center">Liste des marques</h1>
	</div>
	<div class="container">
		<div>
			<button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Ajouter une marque 😁</button>
		</div>
		<table class="table table-striped">
			<thead>
				<tr>
					<th scope="col">Num</th>
					<th scope="col">Nom</th>
					<th scope="col">Prix depart</th>
					<th scope="col">marque</th>
				</tr>
			</thead>
			<tbody>
				{% for model in models %}
					<tr>
						<th scope="row">{{ model.id }}</th>
						<td>{{ model.nom }}</td>
						<td>{{model.prixDepart}}</td>
						<td>Ici IMG</td>
						<td>
							<a class='text-decoration-none' id='btn-view' href="{{path('model', {'id': model.id})}}">
								<button class="btn btn-outline-info" >👀</button>
							</a>
							<a class='text-decoration-none' href="{{path('model_delete', {'id': model.id})}}">
								<button class="btn btn-outline-danger">❌</button>
							</a>
						</td>
					</tr>
				{% else %}
					<tr>
						<td colspan="4" class="text-center">Pas de marques Mr 😑</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
		<form method="post" action="" enctype="multipart/form-data">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h1 class="modal-title fs-5" id="staticBackdropLabel">Ajouter un modèle</h1>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body">
						{{ form(ajout) }}

						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
							<button type="submit" class="btn btn-success">Sauvegarder</button>
						</div>
					</div>
				</div>
			</form>
		</div>
	{% endblock %}

templates/model/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container w-50">
		<div class="py-5 text-center">
			<p class="lead">Modifier votre model : {{UnModel.nom}}</p>
		</div>

		<div class="row g-5">
			<div class="col-md-4 col-lg-4 order-md-last">
				<h4 class="d-flex justify-content-between align-items-center mb-3">
					<span class="text-primary">Le modèle
					</span>
				</h4>
				<ul class="list-group mb-3">
					<li class="list-group-item d-flex justify-content-between lh-sm">
						<div>
							<h6 class="my-0">Nom
							</h6>
						</div>
						<span class="text-muted">{{UnModel.nom}}</span>
					</li>
					<li class="list-group-item d-flex justify-content-between lh-sm">
						<div>
							<h6 class="my-0">Prix
							</h6>
						</div>
						<span class="text-muted">{{UnModel.prixDepart}}</span>
					</li>
				</ul>
			</div>
			<div class="col-md-7 col-lg-7 order-md-last">
				<h4 class="d-flex justify-content-between align-items-center mb-3">
					<span class="text-primary">Modifications
					</span>
				</h4>
                {{form(edit)}}
			</div>
		</div>
	</div>
{% endblock %}